
services:
  web:
    image: php:8.2-apache
    container_name: sovpadem_web
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./composer.json:/var/www/composer.json
      - ./vendor:/var/www/vendor
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_ENV=prod
      - MYSQL_HOST=db
    command: >
      bash -c "apt-get update && apt-get install -y libzip-dev zip unzip git && 
      docker-php-ext-install pdo pdo_mysql zip && 
      a2enmod rewrite headers && 
      php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
      php -r \"unlink('composer-setup.php');\" &&
      cd /var/www && /usr/local/bin/composer install &&
      php /var/www/html/init_db.php &&
      apache2-foreground"
    labels:
      - traefik.enable=true
      - traefik.http.routers.sovpadem.rule=Host(`sovpadem.ru`)
      - traefik.http.routers.sovpadem.entrypoints=websecure
      - traefik.http.routers.sovpadem.tls=true
      - traefik.http.routers.sovpadem.tls.certresolver=letsencrypt
      - traefik.http.services.sovpadem.loadbalancer.server.port=80
    networks:
      - web
    profiles:
      - prod

  db:
    image: mysql:8.0
    container_name: sovpadem_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sovpadem}
      MYSQL_USER: ${MYSQL_USER:-sovpadem_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sovpadem_password}
    volumes:
      - sovpadem-mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d # Добавляем инициализацию БД
    networks:
      - web
    profiles:
      - prod

  web_dev:
    image: php:8.2-apache
    container_name: sovpadem_web_dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./composer.json:/var/www/composer.json
      - ./vendor:/var/www/vendor
    depends_on:
      - db_dev
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
      - APP_ENV=dev
      - MYSQL_HOST=db_dev
    command: >
      bash -c "apt-get update && apt-get install -y libzip-dev zip unzip git && 
      docker-php-ext-install pdo pdo_mysql zip && 
      a2enmod rewrite headers && 
      php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
      php -r \"unlink('composer-setup.php');\" &&
      cd /var/www && /usr/local/bin/composer install &&
      php /var/www/html/init_db.php &&
      apache2-foreground"
    networks:
      - web
    profiles:
      - dev

  db_dev:
    image: mysql:8.0
    platform: linux/arm64
    container_name: sovpadem_db_dev
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sovpadem}
      MYSQL_USER: ${MYSQL_USER:-sovpadem_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sovpadem_password}
    volumes:
      - sovpadem-mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d # Добавляем инициализацию БД
    networks:
      - web
    profiles:
      - dev

volumes:
  sovpadem-mysql-data:

networks:
  web:
    external: true