
services:
  web:
    image: php:8.2-apache
    container_name: sovpadem_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./composer.json:/var/www/composer.json
      - ./vendor:/var/www/vendor
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "apt-get update && apt-get install -y libzip-dev zip unzip git && 
      docker-php-ext-install pdo pdo_mysql zip && 
      a2enmod rewrite headers && 
      php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" &&
      php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
      php -r \"unlink('composer-setup.php');\" &&
      cd /var/www && /usr/local/bin/composer install &&
      apache2-foreground"

  db:
    image: mysql:8.0
    container_name: sovpadem_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sovpadem
      MYSQL_USER: sovpadem_user
      MYSQL_PASSWORD: sovpadem_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: