name: Deploy Sovpadem

concurrency: production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Инициализация репозитория"
        uses: actions/checkout@v4

      - name: "Заполнение переменных среды"
        run: |
          echo "APP_ENV=prod" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: "Создадим каталог проекта"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /var/www/sovpadem.ru

      - name: "Скопируйте файлы приложения на удаленный сервер"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "/var/www/sovpadem.ru"

  publish:
    name: "Запуск контейнера"
    runs-on: ubuntu-latest
    needs: [deploy]
    environment: production
    steps:
      - name: "Создадим веб-сеть и запустите docker compose"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e  # остановка при любой ошибке
            echo "🚀 Начинаем развертывание..."
            echo "🌐 Проверяем и создаем сеть Docker..."
            docker network ls | grep web || docker network create web
            cd /var/www/sovpadem.ru/
            echo "🔐 Настраиваем права доступа..."
            chown -R www-data:www-data ./src
            find ./src -type d -exec chmod 755 {} \;
            find ./src -type f -exec chmod 644 {} \;
            echo "🔄 Запускаем в продакшн режиме..."
            make prod
            echo "🔍 Проверяем статус контейнеров..."
            docker compose ps || exit 1

  test:
    name: "Проверим, что сайт запущен"
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Check website
        uses: wei/curl@v1
        with:
          args: https://sovpadem.ru/

  alert:
    name: "Уведомление о деплое"
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: "Отправить уведомление, что всё развернулось"
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} создал commit:
            Commit: ${{ github.event.commits[0].message }}
            
            Репозиторий: ${{ github.repository }}
            
            Изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Сайт доступен по адресу: https://sovpadem.ru/